CREATE TABLE MARCA (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR(20) NOT NULL,
    CONSTRAINT ID_MARCA_PK PRIMARY KEY (ID)
);

CREATE TABLE PRENDA (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    TIPO_PRENDA VARCHAR(20) NOT NULL,
    COLOR VARCHAR(20) NOT NULL,
    PRECIO DECIMAL(7,2),
    SEGUNDA_MANO BOOLEAN,
    MARCA INTEGER,
    FECHA_CREACION DATE,
    CONSTRAINT ID_PRENDA_PK PRIMARY KEY (ID),
    CONSTRAINT MARCA_PRENDA_FK FOREIGN KEY (MARCA) REFERENCES MARCA (ID)
);